# Generated by Django 5.2.6 on 2025-10-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoApp', '0002_demdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticFigure',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('figure_file', models.ImageField(blank=True, null=True, upload_to='figures/')),
                ('date_taken', models.DateField(blank=True, null=True)),
                ('region', models.CharField(choices=[('Long An', 'Long An'), ('Hồ Chí Minh', 'Hồ Chí Minh'), ('Đồng Nai', 'Đồng Nai'), ('Bình Dương', 'Bình Dương'), ('Tây Ninh', 'Tây Ninh'), ('Bến Tre', 'Bến Tre'), ('An Giang', 'An Giang'), ('Kiên Giang', 'Kiên Giang'), ('Cần Thơ', 'Cần Thơ'), ('Vĩnh Long', 'Vĩnh Long'), ('Trà Vinh', 'Trà Vinh'), ('Sóc Trăng', 'Sóc Trăng'), ('Bạc Liêu', 'Bạc Liêu'), ('Cà Mau', 'Cà Mau')], help_text='figure')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
